/*
* generated by Xtext
*/
package org.xtest.ui.contentassist;

import org.xtest.ui.contentassist.AbstractXTestProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XTestProposalProvider extends AbstractXTestProposalProvider {

}
