/*
 * generated by Xtext
 */
package org.xtest.ui.contentassist;


/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to
 * customize content assistant
 */
public class XTestProposalProvider extends AbstractXTestProposalProvider {

}
