/*
 * generated by Xtext
 */
package org.xtest.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtest.ui.internal.XTestActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XTestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XTestActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XTestActivator.getInstance().getInjector(XTestActivator.ORG_XTEST_XTEST);
	}
	
}
