/*
* generated by Xtext
*/
package org.xtest.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtest.services.XTestGrammarAccess;

public class XTestParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XTestGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtest.parser.antlr.internal.InternalXTestParser createParser(XtextTokenStream stream) {
		return new org.xtest.parser.antlr.internal.InternalXTestParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Body";
	}
	
	public XTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
